//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeverManagementSystemMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public int CredentialID { get; set; }
        public int ServerID { get; set; }
        public string LoginId { get; set; }
        public string LoginPwd { get; set; }
        public Nullable<System.DateTime> CredDate { get; set; }
        public Nullable<System.DateTime> CredUser { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string ModUSer { get; set; }
        public bool Status { get; set; }
    }
}
