//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeverManagementSystemMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ServerManagementEntities : DbContext
    {
        public ServerManagementEntities()
            : base("name=ServerManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<VPNUser> VPNUsers { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Usage_Detail> Usage_Detail { get; set; }
    
        public virtual ObjectResult<spGetSeverInfo_Result> spGetSeverInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetSeverInfo_Result>("spGetSeverInfo");
        }
    }
}
