//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeverManagementSystemMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPNUser
    {
        public int VPNUSerId { get; set; }
        public string VPNUserName { get; set; }
    }
}
